appName: react-app
appReplicas: 1
appImage: mycodeschool/crud-client-api
appVersion: 16.03.2025.08.35.19
containerPort: 3000
containerTargetPort: 3000
namespace: default
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi
configMap:
  name: app-config
  items:
    - key: config.json
      path: config.json
volumeMounts:
  - name: app-config-volume
    mountPath: /app/build/config/config.json
    subPath: config.json
volumes:
  - name: app-config-volume
    configMap:
      name: app-config
      items:
        - key: config.json
          path: config.json