apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: default
data:
  DB_HOST: "mysql"
  DB_NAME: "testdb"
  DB_USER: "testuser"
  config.json: |
    {
        "BASE_URL": "http://localhost"
    }
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'spring-boot'
        scrape_interval: 5s
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets:
              - 'kube-land.default.svc.cluster.local:8082'
              - 'kube-ms1.default.svc.cluster.local:8081'
  grafana-datasources.yml: |
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          url: http://prometheus:9090
          access: proxy
          isDefault: true