appName:  kibana
appReplicas: 1
appImage: docker.elastic.co/kibana/kibana
appVersion: 8.12.1
containerPort: 5601
containerTargetPort: 5601
containerEnvVars:
  - name: SERVER_BASEPATH
    value: "/kibana"
  - name: SERVER_REWRITEBASEPATH
    value: "true"
  - name: SERVER_SAMESITECOOKIES
    value: "None"
  - name: ELASTICSEARCH_HOSTS
    value: "http://elasticsearch:9200"
  - name: ELASTICSEARCH_USERNAME
    value: "kibana_system"
  - name: ELASTICSEARCH_PASSWORD
    valueFrom:
      secretKeyRef:
        name: kibana-secret
        key: kibana_password
  - name: TELEMETRY_ENABLED
    value: "false"
namespace: default
storageClass: local-path
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi
liveness:
  path: /
  initialDelaySeconds: 15
  periodSeconds: 20
readiness:
  path: /
  initialDelaySeconds: 5
  periodSeconds: 10
