apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.auth.appName }}
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.auth.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.auth.appName }}
    spec:
      containers:
        - name: {{ .Values.auth.appName }}
          image: {{ include "crud-proj.image" (dict "image" .Values.images.authService "global" .Values.global) }}
          imagePullPolicy: {{ .Values.images.authService.pullPolicy }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.auth.springProfile }}
          ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.auth.appName }}
  namespace: default
spec:
  type: ClusterIP
  ports:
    - port: 8082
      targetPort: 8082
  selector:
    app: {{ .Values.auth.name }}