apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-land
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-land
  template:
    metadata:
      labels:
        app: kube-land
    spec:
      containers:
        - name: kube-land
          image: {{ include "crud-proj.image" (dict "image" .Values.images.authService "global" .Values.global) }}
          imagePullPolicy: {{ .Values.images.authService.pullPolicy }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "helm"
          ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: kube-land
  namespace: default
spec:
  type: ClusterIP
  ports:
    - port: 8082
      targetPort: 8082
  selector:
    app: kube-land