apiVersion: apps/v1
kind: Deployment
metadata:
{{ include "app.metadata" . | indent 2 }}
spec:
  replicas: {{ .Values.appReplicas }}
  selector:
    matchLabels:
{{ include "app.selectorLabels" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "app.selectorLabels" . | indent 8 }}
    spec:
      containers:
        - name: {{ .Values.appName }}
          image: "{{ .Values.appImage }}:{{.Values.appVersion}}"
          ports:
            - containerPort: {{.Values.containerPort}}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readiness.path }}
              port: {{ .Values.containerPort }}
            initialDelaySeconds: {{ .Values.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.readiness.periodSeconds }}
          livenessProbe:
            httpGet:
              path: {{ .Values.liveness.path }}
              port: {{ .Values.containerPort }}
            initialDelaySeconds: {{ .Values.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.liveness.periodSeconds }}
          {{- if .Values.containerEnvFrom }}
          envFrom:
{{ toYaml .Values.containerEnvFrom | indent 12 }}
          {{- end }}
---
apiVersion: v1
kind: Service
metadata:
{{ include "app.metadata" . | indent 2 }}
spec:
  type: ClusterIP
  ports:
    - port:  {{.Values.containerPort}}
      targetPort:  {{.Values.containerTargetPort}}
  selector:
{{ include "app.selectorLabels" . | indent 4 }}
