apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: default
data:
  DB_HOST: "mysql"
  DB_NAME: "testdb"
  DB_USER: "testuser"
  config.json: |
    {
<<<<<<< HEAD:configmap.yaml
      "BASE_URL": "http://react-app.local"
=======
      "BASE_URL": "http://localhost"
>>>>>>> feat/implement-elk-refactor:configs.yaml
    }