appName: prometheus
appReplicas: 1
appImage: prom/prometheus
appVersion: latest
containerPort: 9090
containerTargetPort: 9090
containerEnvVars: []
containerEnvFrom: []
namespace: default
storageClass: local-path
resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 400m
    memory: 512Mi
liveness:
  path: /
  initialDelaySeconds: 15
  periodSeconds: 20
readiness:
  path: /
  initialDelaySeconds: 5
  periodSeconds: 10
