appName: zipkin
appReplicas: 1
appImage: openzipkin/zipkin
appVersion:
containerPort: 9411
containerTargetPort: 9411
namespace: default
storageClass: local-path
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi
liveness:
  path: /
  initialDelaySeconds: 15
  periodSeconds: 20
readiness:
  path: /
  initialDelaySeconds: 5
  periodSeconds: 10
