appName: zipkin
appReplicas: 1
appImage: openzipkin/zipkin
appVersion:
containerPort: 9411
containerTargetPort: 9411
containerEnvVars: []
containerEnvFrom: []
namespace: default
storageClass: local-path
resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 400m
    memory: 512Mi
liveness:
  path: /
  initialDelaySeconds: 15
  periodSeconds: 20
readiness:
  path: /
  initialDelaySeconds: 5
  periodSeconds: 10
