appName: infra
appReplicas: 1
appImage: nginx
appVersion: latest
containerPort: 7651
containerTargetPort: 7561
containerEnvVars: []
namespace: default
storageClass: local-path
resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 400m
    memory: 512Mi
liveness:
  path: /
  initialDelaySeconds: 15
  periodSeconds: 20
readiness:
  path: /
  initialDelaySeconds: 5
  periodSeconds: 10
