appName:  logstash
appReplicas: 1
appImage: docker.elastic.co/logstash/logstash
appVersion: 8.12.1
containerPort: 3100
containerTargetPort: 3100
containerEnvVars:
  - name: ELASTIC_PASSWORD
    valueFrom:
      secretKeyRef:
        name: logstash-secret
        key: elastic_password
  - name: CONFIG_STRING
    value: |
      input {
        tcp {
          port => 3100
          codec => json_lines
        }
      }
      output {
        elasticsearch {
          hosts => ["http://elasticsearch:9200"]
          user => "elastic"
          password => "${ELASTIC_PASSWORD}"
          ssl => false
        index => "kube-logs"
      }
    }
namespace: default
storageClass: local-path
resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 400m
    memory: 512Mi
liveness:
  path: /
  initialDelaySeconds: 15
  periodSeconds: 20
readiness:
  path: /
  initialDelaySeconds: 5
  periodSeconds: 10
