apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: {{ .Values.namespace }}
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'spring-boot'
        scrape_interval: 5s
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets:
              - 'kube-land.default.svc.cluster.local:8082'
              - 'kube-ms1.default.svc.cluster.local:8081'
