apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications-service
  template:
    metadata:
      labels:
        app: notifications-service
    spec:
      containers:
        - name: notifications-service
          image: {{ include "crud-proj.image" (dict "image" .Values.images.notificationsService "global" .Values.global) }}
          imagePullPolicy: {{ .Values.images.notificationsService.pullPolicy }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "helm"
          ports:
            - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: notifications-service
  namespace: default
spec:
  type: ClusterIP
  ports:
    - port: 8083
      targetPort: 8083
  selector:
    app: notifications-service