# MySQL Persistent Volume Claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "crud-proj.fullname" . }}-mysql-pvc
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "crud-proj.mysql.labels" . | nindent 4 }}
spec:
  {{- if .Values.global.storageClass }}
  storageClassName: {{ .Values.global.storageClass }}
  {{- end }}
  accessModes:
    - {{ .Values.mysql.storage.accessMode }}
  resources:
    requests:
      storage: {{ .Values.mysql.storage.size }}

---
# ElasticSearch Persistent Volume Claim

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "crud-proj.fullname" . }}-es-pvc
spec:
  storageClassName: {{ .Values.global.storageClass }}
  accessModes:
    - {{ .Values.elasticsearch.storage.accessMode }}
  resources:
    requests:
      storage: {{ .Values.elasticsearch.storage.size }}

---
# RabbitMQ Persistent Volume Claim

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-pvc
  namespace: {{ .Values.global.namespace }}
spec:
  storageClassName: {{ .Values.global.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
# Keycloak Persistent Volume Claim

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-pvc
  namespace: {{ .Values.global.namespace }}
spec:
  storageClassName: {{ .Values.global.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
  namespace: {{ .Values.global.namespace }}
spec:
  storageClassName: {{ .Values.global.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: {{ .Values.global.namespace }}
spec:
  storageClassName: {{ .Values.global.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi            


