apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "crud-app.fullname" . }}-config
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "crud-app.labels" . | nindent 4 }}
data:
  # Database connection configuration
  DB_HOST: "{{ include "crud-app.fullname" . }}-mysql"
  DB_NAME: {{ .Values.mysql.database | quote }}
  DB_USER: {{ .Values.mysql.user | quote }}

  # Frontend application configuration
  config.json: |
    {
      "BASE_URL": {{ .Values.app.baseUrl | quote }}
    }

  # Prometheus monitoring configuration
  prometheus.yml: |
    global:
      scrape_interval: {{ .Values.prometheus.scrapeInterval }}
      evaluation_interval: {{ .Values.prometheus.evaluationInterval }}

    scrape_configs:
      - job_name: 'spring-boot-services'
        scrape_interval: 5s
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets:
              {{- if .Values.features.database }}
              - '{{ include "crud-app.fullname" . }}-auth-service.{{ .Values.global.namespace }}.svc.cluster.local:{{ .Values.services.authService.port }}'
              - '{{ include "crud-app.fullname" . }}-command-service.{{ .Values.global.namespace }}.svc.cluster.local:{{ .Values.services.commandService.port }}'
              {{- end }}

      {{- if .Values.prometheus.enabled }}
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      {{- end }}

      {{- if .Values.grafana.enabled }}
      - job_name: 'grafana'
        static_configs:
          - targets: ['{{ include "crud-app.fullname" . }}-grafana:3000']
      {{- end }}

  # Grafana datasource configuration
  grafana-datasources.yml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: {{ include "crud-app.prometheus.url" . }}
        access: proxy
        isDefault: true
        editable: true
