apiVersion: v1
kind: Secret
metadata:
  name: {{ include "crud-app.fullname" . }}-db-credentials
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "crud-app.labels" . | nindent 4 }}
type: Opaque
data:
  # Database passwords (base64 encoded)
  DB_PASSWORD: {{ .Values.mysql.password | b64enc }}
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.rootPassword | b64enc }}

---
{{- if .Values.features.logging }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "crud-app.fullname" . }}-elk-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "crud-app.labels" . | nindent 4 }}
type: Opaque
data:
  # ELK stack passwords (base64 encoded)
  elastic_password: {{ .Values.elasticsearch.password | b64enc }}
  kibana_password: {{ .Values.kibana.password | b64enc }}
{{- end }}
