appName: kube-land
appReplicas: 1
appImage: mycodeschool/crud-auth-api
appVersion: 29.03.2025.16.35.52
containerPort: 8082
containerTargetPort: 8082
namespace: default
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi
env:
  - name: SPRING_PROFILES_ACTIVE
    value: "kubernetes"