apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:24.0.4
          args:
            - "start"
            - "--import-realm"
          ports:
            - containerPort: 8080
          env:
            # Admin user/pass din secret
            - name: KEYCLOAK_ADMIN
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: adminUser
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: adminPassword

            # Config baza de date
            - name: KC_DB
              value: mysql
            - name: KC_DB_URL
              value: jdbc:mysql://mysql-service:3306/testdb
            - name: KC_DB_USERNAME
              value: testuser
            - name: KC_DB_PASSWORD
              value: testpass

            # Opțiuni Keycloak
            - name: KC_HTTP_ENABLED
              value: "true"
            - name: KC_HOSTNAME_STRICT
              value: "false"
            - name: KC_HOSTNAME_STRICT_HTTPS
              value: "false"
            - name: KC_PROXY
              value: passthrough
            - name: KC_HEALTH_ENABLED
              value: "true"
            - name: KC_METRICS_ENABLED
              value: "true"
            - name: KC_FEATURES
              value: token-exchange,admin-fine-grained-authz
            - name: KC_LOG_LEVEL
              value: INFO
            - name: KC_LOG_CONSOLE_OUTPUT
              value: json
            - name: KC_HOSTNAME
              value: keycloak.local

          volumeMounts:
            - name: keycloak-data
              mountPath: /opt/keycloak/data
            - name: realm-export
              mountPath: /opt/keycloak/data/import
              readOnly: true

      volumes:
        - name: keycloak-data
          persistentVolumeClaim:
            claimName: keycloak-pvc
        - name: realm-export
          configMap:
            name: app-config
            items:
              - key: realm-export.json
                path: realm-export.json

---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
spec:
  selector:
    app: keycloak
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: https
      port: 8443
      targetPort: 8443
    - name: management
      port: 9000
      targetPort: 9000
  type: ClusterIP
