apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: default
type: Opaque
data:


  DB_PASSWORD: dGVzdHBhc3M=

---

apiVersion: v1
kind: Secret
metadata:
  name: elk-secrets
  namespace: default
type: Opaque
data:
  # echo -n 'passwOrd' | base64
  elastic_password: cGFzc3dPcmQ=
  # echo -n 'passwOrd' | base64
  kibana_password: cGFzc3dPcmQ=
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
type: Opaque
data:
  adminUser: YWRtaW4=              # base64(admin)
  adminPassword: YWRtaW4=          # base64(admin)

---
apiVersion: v1
kind: Secret
metadata:
  name: react-env-secret
type: Opaque
stringData:
  env-config.js: |
    window._env_ = {
      KEYCLOAK_CLIENT_SECRET: "oZTKDqmy20gnH1lWdpBHbbvRJ8gmCuXu"
    }
