
{{- if and .Values.elasticsearch.enabled .Values.features.logging }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "crud-app.fullname" . }}-elasticsearch
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "crud-app.elasticsearch.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9200
      targetPort: http
      protocol: TCP
    - name: transport
      port: 9300
      targetPort: transport
      protocol: TCP
  selector:
    {{- include "crud-app.elasticsearch.selectorLabels" . | nindent 4 }}
{{- end }}