appName:  kube-ms1
appReplicas: 1
appImage: mycodeschool/crud-command-api
appVersion: 29.03.2025.16.35.20
containerPort: 8081
containerTargetPort: 8081
containerEnvVars:
  - name: SPRING_PROFILES_ACTIVE
    value: "kubernetes"
namespace: default
storageClass: local-path
resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 400m
    memory: 512Mi
liveness:
  path: /
  initialDelaySeconds: 15
  periodSeconds: 20
readiness:
  path: /
  initialDelaySeconds: 5
  periodSeconds: 10
