appName: kube-ms1
appReplicas: 1
appImage: mycodeschool/crud-command-api
appVersion: 29.03.2025.16.35.20
containerPort: 8081
containerTargetPort: 8081
namespace: default
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi
env:
  - name: SPRING_PROFILES_ACTIVE
    value: "kubernetes"