apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "crud-app.fullname" . }}-react-app
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "crud-app.react-app.labels" . | nindent 4 }}
spec:
  # Deployment strategy
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  # Number of replicas
  replicas: {{ .Values.reactApp.replicas | default 1 }}

  # Pod selection
  selector:
    matchLabels:
      {{- include "crud-app.react-app.selectorLabels" . | nindent 6 }}

  # Pod template
  template:
    metadata:
      labels:
        {{- include "crud-app.react-app.selectorLabels" . | nindent 8 }}
      annotations:
        # Force restart on config changes
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}

    spec:
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.global.imagePullSecrets | nindent 8 }}
      {{- end }}

      containers:
        - name: react-app
          image: {{ include "crud-app.image" (dict "image" .Values.images.reactApp "global" .Values.global) }}
          imagePullPolicy: {{ .Values.images.reactApp.pullPolicy }}

          # Environment variables
          env:
            - name: PORT
              value: {{ .Values.services.reactApp.port | quote }}
            - name: NODE_ENV
              value: "production"
            # API endpoints
            - name: REACT_APP_AUTH_SERVICE_URL
              value: "{{ .Values.app.baseUrl }}/api"
            - name: REACT_APP_COMMAND_SERVICE_URL
              value: "{{ .Values.app.baseUrl }}/ms1"

          # Container ports
          ports:
            - name: http
              containerPort: {{ .Values.services.reactApp.port }}
              protocol: TCP

          # Volume mounts for configuration
          volumeMounts:
            - name: app-config-volume
              mountPath: /app/build/config/config.json
              subPath: config.json
              readOnly: true

          # Resource limits
          {{- if .Values.reactApp.resources }}
          resources:
            {{- toYaml .Values.reactApp.resources | nindent 12 }}
          {{- end }}

          # Health checks
          {{- if .Values.healthChecks.enabled }}
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          {{- end }}

      # Volumes
      volumes:
        - name: app-config-volume
          configMap:
            name: {{ include "crud-app.fullname" . }}-config
            items:
              - key: config.json
                path: config.json
