apiVersion: batch/v1
kind: Job
metadata:
  name: kibana-setup
  namespace: {{ .Values.namespace }}
spec:
  backoffLimit: 0      # Retry only once if it fails
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: elk-setup
          image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1
          imagePullPolicy: IfNotPresent
          resources:
{{ toYaml .Values.resources | indent 12 }}
          env:
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elk-secrets
                  key: elastic_password
            - name: KIBANA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elk-secrets
                  key: kibana_password

          # ⬇️ switch from bash to sh
          command: ["sh", "-c"]
          args:
            - |
              echo "Waiting for Elasticsearch availability";
              until curl -s http://elasticsearch:9200 | grep -q "missing authentication credentials"; do
                echo "Elasticsearch not ready, sleeping 10s..."
                sleep 10
              done

              echo "Setting kibana_system password";
              until curl -s -X POST -u "elastic:${ELASTIC_PASSWORD}" \
                    -H "Content-Type: application/json" \
                    -d "{\"password\":\"${KIBANA_PASSWORD}\"}" \
                    http://elasticsearch:9200/_security/user/kibana_system/_password \
                    | grep -q "^{}"; do
                echo "Retrying in 10s..."
                sleep 10
              done

              echo "All done! Kibana should now authenticate with the 'kibana_system' user."
