apiVersion: apps/v1
kind: StatefulSet
metadata:
{{ include "app.metadata" . | indent 2 }}
spec:
  serviceName: {{ .Values.serviceName }}
  replicas: {{ .Values.appReplicas }}
  selector:
    matchLabels:
{{ include "app.selectorLabels" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "app.selectorLabels" . | indent 8 }}
    spec:
      {{- if .Values.initContainers }}
      initContainers:
      {{- range .Values.initContainers }}
        - name: {{ .name }}
          image: {{ .image }}
          command: {{ .command }}
          {{- if .volumeMounts }}
          volumeMounts:
{{ toYaml .volumeMounts | indent 12 }}
          {{- end }}
          {{- if .env }}
          env:
{{ toYaml .env | indent 12 }}
          {{- end }}
      {{- end }}
      {{- end }}
      containers:
        - name: {{ .Values.appName }}
          image: "{{ .Values.appImage }}:{{.Values.appVersion}}"
          {{- if .Values.ports }}
          ports:
{{ toYaml .Values.ports | indent 12 }}
          {{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          env:
          {{- if .Values.env }}
{{ toYaml .Values.env | indent 12 }}
          {{- end }}
          {{- if .Values.secretRefs }}
          {{- range .Values.secretRefs }}
          - name: {{ .name }}
            valueFrom:
              secretKeyRef:
                name: {{ .secretName }}
                key: {{ .secretKey }}
          {{- end }}
          {{- end }}
          {{- if .Values.volumeMounts }}
          volumeMounts:
{{ toYaml .Values.volumeMounts | indent 12 }}
          {{- end }}
      {{- if .Values.volumes }}
      volumes:
{{ toYaml .Values.volumes | indent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
{{ include "app.metadata" . | indent 2 }}
spec:
  type: ClusterIP
  selector:
{{ include "app.selectorLabels" . | indent 4 }}
  ports:
    - name: http
      port: 9200
      targetPort: 9200
    - name: transport
      port: 9300
      targetPort: 9300
