apiVersion: v2
name: crud-proj
description: A Helm chart for backend application with MySQL
type: application
version: 0.1.0    # Versiunea chart-ului
appVersion: "1.0.0"  # Versiunea aplicației tale
