global:
  namespace: default              # Target Kubernetes namespace
  storageClass: local-path       # Storage class for persistent volumes
  imageRegistry: ""              # Global image registry prefix (optional)
  imagePullSecrets: []           # Image pull secrets if needed

# MySQL Configuration  
mysql:
  enabled: true                   # Enable/disable MySQL deployment
  image:
    repository: mysql
    tag: "8.0"
    pullPolicy: IfNotPresent

  # Database configuration
  database: testdb               # Database name
  user: testuser                # Database user
  password: testpass            # Database password (will be base64 encoded)
  rootPassword: testpass        # Root password (will be base64 encoded)

  # Storage configuration
  storage:
    size: 5Gi                   # Persistent volume size
    accessMode: ReadWriteOnce   # Access mode for PVC

  # Resource limits and requests
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "500m"

# Elasticsearch Configuration  
elasticsearch:
  storage:
    size: 5Gi
    accessMode: ReadWriteOnce
  password: passwOrd # password (will be base64 encoded)


images:
  # Command service image
  commandService:
    repository: mycodeschool/crud-command-api
    tag: "24.09.2025.15.13.44-dev"
    pullPolicy: IfNotPresent


  # Command service image
  notificationsService:
    repository: mycodeschool/crud-notification-api
    tag: "29.09.2025.13.22.48-dev"
    pullPolicy: IfNotPresent


  authService:
    repository: mycodeschool/crud-auth-api
    tag: "29.09.2025.13.42.23-prod"
    pullPolicy: IfNotPresent


  # Elastic image
  elasticsearch:
    repository: docker.elastic.co/elasticsearch/elasticsearch
    tag: "8.12.1"
    pullPolicy: IfNotPresent


  
  # Logstash image
  logstash:
    repository: docker.elastic.co/logstash/logstash
    tag: "8.12.1"
    pullPolicy: IfNotPresent