apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: default
spec:
  replicas: {{ .Values.appReplicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - name: {{ .Values.appName }}
          image: "{{ .Values.appImage }}:{{ .Values.appVersion }}"
          env:
            {{- range .Values.containerEnvVars }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          volumeMounts:
            - name: grafana-datasources
              mountPath: /etc/grafana/provisioning/datasources
              readOnly: true
            - name: grafana-data
              mountPath: /var/lib/grafana
      volumes:
        - name: grafana-datasources
          configMap:
            name: app-config
            items:
              - key: grafana-datasources.yml
                path: grafana-datasources.yml
        - name: grafana-data
          persistentVolumeClaim:
            claimName: grafana-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  namespace: default
spec:
  selector:
    app: {{ .Values.appName }}
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.containerPort }}
      targetPort: {{ .Values.containerTargetPort }}
