apiVersion: v1
kind: Service
metadata:
  name: {{ include "crud-proj.fullname" . }}-mysql-service
  namespace: default
spec:
  ports:
    - port: 3306
      targetPort: 3306
  clusterIP: None
  selector:
    app: {{ include "crud-proj.fullname" . }}-mysql
