apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: {{ .Values.namespace }}
type: Opaque
data:


  DB_PASSWORD: dGVzdHBhc3M=

---

apiVersion: v1
kind: Secret
metadata:
  name: elk-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  # echo -n 'passwOrd' | base64
  elastic_password: cGFzc3dPcmQ=
  # echo -n 'passwOrd' | base64
  kibana_password: cGFzc3dPcmQ=
