apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-ms1
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-ms1
  template:
    metadata:
      labels:
        app: kube-ms1
    spec:
      containers:
        - name: command-service
          image: {{ include "crud-proj.image" (dict "image" .Values.images.commandService "global" .Values.global) }}
          imagePullPolicy: {{ .Values.images.commandService.pullPolicy }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "helm"
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: kube-ms1
  namespace: default
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: kube-ms1