appName: mysql-service
appReplicas: 1
appImage: mysql
appVersion: 8.0
containerPort: 3306
containerTargetPort: 3306
containerEnvVars:
  - name: MYSQL_ROOT_PASSWORD
    valueFrom:
      secretKeyRef:
        name: mysql-secret
        key: DB_PASSWORD
  - name: MYSQL_DATABASE
    valueFrom:
      configMapKeyRef:
        name: mysql-config
        key: DB_NAME
  - name: MYSQL_USER
    valueFrom:
      configMapKeyRef:
        name: mysql-config
        key: DB_USER
  - name: MYSQL_PASSWORD
    valueFrom:
      secretKeyRef:
        name: mysql-secret
        key: DB_PASSWORD
namespace: default
storageClass: local-path
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi
liveness:
  path: /
  initialDelaySeconds: 15
  periodSeconds: 20
readiness:
  path: /
  initialDelaySeconds: 5
  periodSeconds: 10
